<#
.SYNOPSIS
  PowerSquad interactive setup. Collects your demo-tenant details and writes a
  git-ignored `.env` at the repo root so the squad can resolve ${PLACEHOLDERS}.

.DESCRIPTION
  Run once after cloning:   pwsh ./setup/setup-powersquad.ps1
  Re-run any time to update values. Existing .env values are shown as defaults
  (press Enter to keep them). Nothing here is committed — .env is git-ignored.
#>

$ErrorActionPreference = 'Stop'
$repoRoot = Split-Path -Parent $PSScriptRoot
$envPath  = Join-Path $repoRoot '.env'

Write-Host ""
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  PowerSquad setup — configure your demo environment" -ForegroundColor Cyan
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  Answers are saved to a git-ignored .env at the repo root."
Write-Host "  Press Enter to keep the [current] value shown in brackets."
Write-Host ""

# Load existing .env (if any) into a hashtable for defaults
$existing = @{}
if (Test-Path $envPath) {
    Get-Content $envPath | ForEach-Object {
        if ($_ -match '^\s*([A-Z_]+)\s*=\s*(.*)$') { $existing[$Matches[1]] = $Matches[2] }
    }
    Write-Host "Found an existing .env — its values are the defaults." -ForegroundColor Yellow
    Write-Host ""
}

function Ask($key, $prompt, $example, [switch]$optional) {
    $cur = $existing[$key]
    $hint = if ($cur) { "[$cur]" } else { "e.g. $example" }
    $tag  = if ($optional) { " (optional)" } else { "" }
    while ($true) {
        $ans = Read-Host "$prompt$tag `n  $hint"
        if ([string]::IsNullOrWhiteSpace($ans)) { $ans = $cur }
        if ([string]::IsNullOrWhiteSpace($ans) -and -not $optional) {
            Write-Host "  ! Required. Please enter a value." -ForegroundColor Red
            continue
        }
        return $ans
    }
}

$vals = [ordered]@{}

Write-Host "-- Demo build target ---------------------------------------" -ForegroundColor Green
$vals.DEMO_ORG_URL     = Ask 'DEMO_ORG_URL'     'Demo org URL' 'https://org12345678.crm.dynamics.com'
# derive host + id from the URL
$u = $vals.DEMO_ORG_URL -replace '^https?://','' -replace '/.*$',''
$vals.DEMO_ORG_HOST    = $u
$vals.DEMO_ORG_ID      = ($u -split '\.')[0]
$vals.ENVIRONMENT_ID   = Ask 'ENVIRONMENT_ID'   'Environment GUID (Admin Center > Environments)' '00000000-0000-0000-0000-000000000000'
$vals.ENVIRONMENT_NAME = Ask 'ENVIRONMENT_NAME' 'Environment display name' 'MyDemoEnv'
$vals.TENANT_ID        = Ask 'TENANT_ID'        'Demo tenant GUID' '00000000-0000-0000-0000-000000000000'
$vals.ADMIN_UPN        = Ask 'ADMIN_UPN'        'Native admin UPN of the demo tenant' 'admin@mydemo.onmicrosoft.com'
$vals.ADMIN_USER       = Ask 'ADMIN_USER'       'Admin short display name' 'Admin' -optional

Write-Host ""
Write-Host "-- Your identity (for context tools) -----------------------" -ForegroundColor Green
$vals.USER_EMAIL       = Ask 'USER_EMAIL'       'Your work email (notifications/test sends)' 'you@example.com' -optional
$vals.USER             = Ask 'USER'             'Your OS username (folder in C:\Users\)' $env:USERNAME
$vals.SCOUT_HOME       = Ask 'SCOUT_HOME'       'Home dir where Scout stores config' "C:\Users\$($vals.USER)" -optional

Write-Host ""
Write-Host "-- Corporate/home tenant (guest scenarios) — optional ------" -ForegroundColor Green
$vals.CORP_TENANT_ID   = Ask 'CORP_TENANT_ID'   'Corporate tenant GUID' '00000000-0000-0000-0000-000000000000' -optional
$vals.CORP_DOMAIN      = Ask 'CORP_DOMAIN'      'Corporate email domain' 'yourcompany.com' -optional
$vals.CORP_EMAIL       = Ask 'CORP_EMAIL'       'Your corporate email' 'you@yourcompany.com' -optional

Write-Host ""
Write-Host "-- Optional context sources & tooling ----------------------" -ForegroundColor Green
$vals.CRM_SALES_HOST      = Ask 'CRM_SALES_HOST'      'CRM Sales host (opportunity context), if any' 'yoursales.crm.dynamics.com' -optional
$vals.CONTENT_LIBRARY_HOST= Ask 'CONTENT_LIBRARY_HOST''Enablement/content library host, if any' 'content.yourcompany.com' -optional
$vals.DEMO_MCP            = Ask 'DEMO_MCP'            'Dataverse MCP server name registered in Scout' 'YOUR-DATAVERSE-MCP'

# --- write .env ---
$lines = @("# PowerSquad .env — generated by setup-powersquad.ps1 on $(Get-Date -Format s)",
           "# This file is git-ignored. Do not commit real tenant details.","")
foreach ($k in $vals.Keys) { $lines += "$k=$($vals[$k])" }
Set-Content -Path $envPath -Value $lines -Encoding UTF8

Write-Host ""
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host "  Saved $([IO.Path]::GetFileName($envPath)) at the repo root." -ForegroundColor Green
Write-Host "  PowerSquad is configured. Activate the squad in Scout to start." -ForegroundColor Green
Write-Host "==========================================================" -ForegroundColor Cyan
Write-Host ""
